---
- name: install packages
  sudo: yes
  with_items: django_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: install pip packages
  sudo: yes
  pip:
    requirements: "{{ requirements_path }}"
    executable: pip-3.2

- name: install python2 psycopg
  sudo: yes
  pip:
    name: psycopg2

- name: migrate DB
  command: python3 manage.py migrate
  args:
    chdir: "{{ api_path }}"
