- name: update apt
  sudo: yes
  apt:
    update_cache: yes

- name: update all packages to the latest version
  sudo: yes
  apt:
    upgrade: dist

- name: remove loclatime
  sudo: yes
  file:
    dest: /etc/localtime
    state: absent

- name: set time zone
  sudo: yes
  file:
    src: /usr/share/zoneinfo/Europe/Belgrade
    dest: /etc/localtime
    owner: root
    group: root
    state: link
    force: yes

- name: install packages
  sudo: yes
  with_items: common_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest
  notify:
    - restart openntpd

- name: download packages
  sudo: yes
  with_items: common_url_packages
  get_url:
    url: "{{ item.url }}"
    dest: "/var/cache/apt/archives/{{ item.name }}.deb"

- name: prepare install script
  sudo: yes
  template:
    src: install.sh.j2
    dest: /tmp/install.sh
    owner: root
    group: root
    mode: 0700

- name: install packages
  sudo: yes
  with_items: common_url_packages
  command: "/tmp/install.sh /var/cache/apt/archives/{{ item.name }}.deb"
  args:
    creates: "/usr/bin/{{ item.name }}"

- name: update apt-file
  sudo: yes
  command: apt-file update
  args:
    creates: /var/cache/apt/apt-file/ftp.de.debian.org_debian_dists_jessie_main_Contents-amd64.gz

- name: disable system wide mpd
  sudo: yes
  service:
    name: mpd
    enabled: no
    state: stopped

- name: configure slim
  sudo: yes
  template:
    src: slim.conf.j2
    dest: /etc/slim.conf
    owner: root
    group: root
  notify:
    - restart slim

- name: configure trackpoint in X
  sudo: yes
  template:
    src: 20-thinkpad.conf.j2
    dest: /usr/share/X11/xorg.conf.d/20-thinkpad.conf
    owner: root
    group: root
  notify:
    - restart slim

- name: configure chromium
  sudo: yes
  with_items: common_chromium_config
  template:
    src: "chromium/{{ item.name }}"
    dest: "/etc/chromium.d/{{ item.name }}"
    owner: root
    group: root

- name: download taskwarrior
  sudo: yes
  get_url:
    url: http://taskwarrior.org/download/task-2.4.0.tar.gz
    dest: /var/cache/apt/taskwarrior.tar.gz
    sha256sum: "6fa595f5b0fdf6ee8031da39e8d009771bda135f265d5f7b59df8046ffd9119e"

- name: unpack taskwarrior
  sudo: yes
  unarchive:
    src: /var/cache/apt/taskwarrior.tar.gz
    dest: /var/cache
    copy: no
    creates: /var/cache/apt/task-2.4.0

- name: prepare to compile taskwarrior
  sudo: yes
  command: cmake -DCMAKE_BUILD_TYPE=release .
  args:
    chdir: /var/cache/task-2.4.0
    creates: /var/cache/task-2.4.0/src/task

- name: compile taskwarrior
  sudo: yes
  command: make
  args:
    chdir: /var/cache/task-2.4.0
    creates: /var/cache/task-2.4.0/src/task

- name: install taskwarrior
  sudo: yes
  command: make install
  args:
    chdir: /var/cache/task-2.4.0
    creates: /usr/local/bin/task

- name: configure wicd
  sudo: yes
  template:
    src: manager-settings.conf.j2
    dest: /etc/wicd/manager-settings.conf
    owner: root
    group: root
    mode: 0600
  notify:
    - restart wicd
