- name: update apt
  sudo: yes
  apt:
    update_cache: yes

- name: update all packages to the latest version
  sudo: yes
  apt:
    upgrade: dist

- name: remove loclatime
  sudo: yes
  file:
    dest: /etc/localtime
    state: absent

- name: set time zone
  sudo: yes
  file:
    src: /usr/share/zoneinfo/Europe/Belgrade
    dest: /etc/localtime
    owner: root
    group: root
    state: link
    force: yes

- name: install packages
  sudo: yes
  with_items: common_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest
