- name: add users
  sudo: yes
  user:
    name: "stefan"
    shell: "/bin/bash"
    groups: "audio,video,sudo"
    append: yes

- name: configure cron 
  sudo: yes
  sudo_user: stefan
  cron:
    name: run ~/bin stuf
    state: present
    job: ~/bin/cron.sh
    minute: "*"

