---
- name: install postgresql packages
  sudo: yes
  with_items: postgresql_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: start postgresql
  sudo: yes
  service:
    name: postgresql
    enabled: yes
    state: started

- name: create DB
  sudo: yes
  sudo_user: postgres
  postgresql_db:
    name: "{{ db_name }}"
    encoding: 'UTF-8'
    template: 'template0'

- name: create DB user
  sudo: yes
  sudo_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    db: "{{ db_name }}"
    role_attr_flags: "CREATEDB"

